apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-04-20T13:57:32Z"
  labels:
    app: jupyter-app
  name: jupyter-svc
  namespace: jupyter
  resourceVersion: "1866"
  uid: d9e4954a-f12e-442c-a3a2-f11f19595501
spec:
  clusterIP: 10.108.220.174
  clusterIPs:
  - 10.108.220.174
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30000
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter-pods
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
